---
title: "599B Final Project (Caz VanDevere, Hanson Shi, Ana Chkeidze"
output:
  html_document:
    df_print: paged
---
 
```{r, libraries, eval=TRUE, echo=FALSE}
# call libraries:
library(ggplot2)
library(haven)
library(Rmisc)
library(ggpubr)
library(tibble)
library(ggrepel)
library(magrittr)
library(dplyr)
library(reshape2)
library(Hmisc)
```

```{r, loaddata, eval=TRUE}
#import data (~250mb):
#datalink='https://dl.dropboxusercontent.com/s/rpjq0x1bgzgdvh1/BRFSS599B.dta'
#brfssdata_orig=read_dta(datalink)
```

```{r loaddata, eval=TRUE, echo=FALSE}
#trim dataframe:
# brfssdata=brfssdata_orig%>%
#    select(mental, stab, ex2014,ex2016, year)%>%
#    filter(!is.na(stab))%>%
#    filter(!is.na(mental))%>%
#    filter(!is.na(year))%>%
#    filter(!is.na(ex2014))%>%
#    filter(!is.na(ex2016))%>%
#    filter((year!=2018))
# write.csv(brfssdata,"brfss.csv",row.names = FALSE)
# head(brfssdata)
# dim(brfssdata)
#brfssdata = read.csv("brfss.csv")
```

```{r}
# import data (~90mb):
brfssdata=read.csv("https://github.com/cazvan/599B_Final/raw/master/brfss.csv")
```


```{r}
#these four states expanded ACA after 2014 ("AK" "LA" "MT" "PA"):
brfssdata$stab=as.character(brfssdata$stab)
bad=unique(brfssdata$stab[(brfssdata$ex2014 == 0 & brfssdata$ex2016 == 1)])
bad
```

```{r}
#Univariate Visualization: barplot
source1="BRFSS Survey Data 2000-2018"
title1="Survey Count by Year"

yearplot=ggplot(data= brfssdata, aes(x=year)) + 
  geom_bar(stat = "count", fill="slateblue") +
  labs(title=title1, x=NULL, y=NULL,caption=source1) +  
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(breaks=c(2000:2017)) +
  theme(panel.background = element_rect(fill = "white",colour = "grey50"),
                              plot.caption = element_text(hjust = 0), # default was 1
                              plot.title = element_text(hjust = 0.5),
                              axis.text.x = element_text(angle = -30, hjust = 0))
yearplot
```

```{r}
#Data prep for multivariate visualization:
#melt dataframe (jk, it's long already)
#pipe=%>% (this is from dplyr) 
dfmelt=brfssdata%>%
  select(year, stab, mental, ex2014)%>%
  filter(stab %nin% bad)%>%
  filter(!is.na(ex2014))%>%
  group_by(year,ex2014)%>%
  mutate(mentavg=mean(mental, na.rm = TRUE))%>%
  ungroup()%>%
  select(year, ex2014,mentavg)%>%
  unique()%>%
  mutate(ex2014=ifelse(ex2014==0, "No Expansion", "Expansion"))
#View(dfmelt)
```

```{r}
# Multi-variate Visualization: line plot
## this plot shows the average mental health number reported each year for 
## states that expanded ACA vs. states that didnt expand ACA
ggplot(dfmelt, aes(x=year, y = mentavg, group = ex2014)) +
  geom_line(aes(color=ex2014)) +
  geom_vline(xintercept=2014) +
  scale_x_continuous(breaks=c(2000:2017)) +
  theme(panel.background = element_rect(fill = "white",colour = "grey50"),
                              plot.caption = element_text(hjust = 0), # default was 1
                              plot.title = element_text(hjust = 0.5),
                              axis.text.x = element_text(angle = 30, hjust = 1)) #+
  #facet_grid(ex2014~.) #gender? Income bracket?

#add mean behavior line? Add annotation instead of reference line for 2014?
```

```{r}
#Graph average mental health by year; each line is a state
dfmeltstab=brfssdata%>%
  select(year, stab, mental, ex2014)%>%
  filter(stab %nin% bad)%>%
  filter(!is.na(ex2014))%>%
  group_by(year,stab,ex2014)%>%
  mutate(mentavg=mean(mental, na.rm = TRUE))%>%
  ungroup()%>%
  select(year, ex2014,mentavg,stab)%>%
  unique()%>%
  mutate(ex2014=ifelse(ex2014==0, "No Expansion", "Expansion"))
```

```{r}
ggplot(dfmeltstab, aes(x=year, y = mentavg, group = stab)) +
  geom_line(aes(color=ex2014)) +
  geom_vline(xintercept=2014) +
  scale_x_continuous(breaks=c(2000:2017)) +
  theme(panel.background = element_rect(fill = "white",colour = "grey50"),
                              plot.caption = element_text(hjust = 0), # default was 1
                              plot.title = element_text(hjust = 0.5),
                              axis.text.x = element_text(angle = -30, hjust = 0))
```


!!!!! EVERYTHING BELOW THIS LINE IS EXPERIMENTAL  !!!!



```{r loaddata, eval=TRUE}
# Create secondary dataframe:
brfsssex=brfssdata_orig%>%
   select(mental, sex, year, stab, ex2014)%>%
   filter(!is.na(mental))%>%
   filter(!is.na(sex))%>%
   filter(!is.na(year))%>%
   filter(!is.na(stab))%>%
   filter(!is.na(ex2014))%>%
   filter((year!=2018))
#head(brfsssex)
#dim(brfsssex)
```

```{r}
#Data prep for multivariate visualization: for sex, edulevel, and income
#melt dataframe (jk, it's long already)
#pipe=%>% (this is from dplyr) 
dfsex=brfssdata_orig%>%
  select(year, stab, mental, ex2014, sex)%>%
  filter(stab %nin% bad)%>%
  filter(!is.na(ex2014))%>%
  group_by(sex,year,ex2014)%>%
  mutate(mentavg=mean(mental, na.rm = TRUE))%>%
  ungroup()%>%
  select(year, ex2014,mentavg,sex)%>%
  unique()%>%
  mutate(ex2014=ifelse(ex2014==0, "No Expansion", "Expansion"))%>%
  filter((year!=2018))

dfsex$sex <- ordered(dfsex$sex,
  levels = c(1,0),
  labels = c("Males", "Females"))

View(dfsex)
```

```{r}
# Multi-variate Visualization: line plot for sex, income, and education level:
## this plot shows the average mental health number reported each year for 
## states that expanded ACA vs. states that didnt expand ACA
titlesex="Negative Mental Health Days by Sex by Expansion Group"

ggplot(dfsex, aes(x=year, y = mentavg, group = ex2014)) +
  geom_line(aes(color=ex2014)) +
  geom_vline(xintercept=2014) +
  scale_x_continuous(breaks=c(2000:2017)) +
  labs(title=titlesex, x=NULL, y=NULL,caption=source1) +
  theme(panel.background = element_rect(fill = "white",colour = "grey50"),
                              plot.caption = element_text(hjust = 0), # default was 1
                              plot.title = element_text(hjust = 0.5),
                              axis.text.x = element_text(angle = 30, hjust = 1)) + facet_grid(sex~.) #gender? Income bracket? Income bracket?
```



```{r}
unique(brfssdata$year)
table(brfssdata$year)
```

```{r loaddata, eval=TRUE}
# Create secondary dataframe:
brfsssex=brfssdata_orig%>%
   select(mental, sex, edu, income, year, stab, ex2014)%>%
   filter(!is.na(mental))%>%
   filter(!is.na(sex))%>%
   filter(!is.na(edu))%>%
   filter(!is.na(income))%>%
   filter(!is.na(year))%>%
   filter(!is.na(stab))%>%
   filter(!is.na(ex2014))%>%
   filter((year!=2018))
#head(brfsssex)
#dim(brfsssex)
```

```{r}
dataset=read.csv('https://github.com/EvanLih/PUBPOL599_Right_To_Work/raw/master/Evan_Lih/Cleaned_RTW_Dataset.csv')
```



